Simple_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"


urlpatterns = [
    path("", views.home, name="home"),
    path(
        "books/",
        views.BookList.as_view(extra_context={"active": "books"}),
        name="book_list",
    ),
    path(
        "<int:pk>/",
        views.BookDetail.as_view(extra_context={"active": "books"}),
        name="book_detail",
    ),
    path(
        "create/",
        views.BookCreate.as_view(extra_context={"active": "books"}),
        name="book_create",
    ),
    path(
        "update/<int:pk>/",
        views.BookUpdate.as_view(extra_context={"active": "books"}),
        name="book_update",
    ),
    path(
        "delete/<int:pk>/",
        views.BookDelete.as_view(extra_context={"active": "books"}),
        name="book_delete",
    ),
    path("numbers/", views.dynamic_url_parameter, name="dynamic_url_parameter"),
]

main/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Book(models.Model):
    title = models.CharField("Book Title", max_length=255)
    author = models.CharField("Book Author", max_length=255)
    image = models.ImageField("Image", upload_to="books/images", null=True, blank=True)
    publish_date = models.DateField("Publish Date")
    created_at = models.DateTimeField("Created at", auto_now_add=True)
    updated_at = models.DateTimeField("Updated at", auto_now=True)
    created_by = models.ForeignKey(
        User,
        related_name="user_books",
        verbose_name="Created By",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:book_detail", args=[self.pk])

main/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ("created_by",)
        widgets = {
            "publish_date": forms.DateInput(attrs={"type": "date"}),
        }

main/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from .forms import BookForm
from .models import Book


def home(request):
    return render(request, "home.html", {"active": "home"})


class BookCreate(SuccessMessageMixin, CreateView):
    model = Book
    template_name = "base/forms/create_update.html"
    success_url = reverse_lazy("main:book_list")
    success_message = "Book successfully created"
    form_class = BookForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            user = self.request.user
            form.instance.created_by = user
            form.save()
        return super().form_valid(form)


class BookUpdate(SuccessMessageMixin, UpdateView):
    model = Book
    template_name = "base/forms/create_update.html"
    success_url = reverse_lazy("main:book_list")
    success_message = "Book successfully updated"
    form_class = BookForm


class BookDelete(SuccessMessageMixin, DeleteView):
    model = Book
    template_name = "base/forms/delete.html"
    success_url = reverse_lazy("main:book_list")
    success_message = "Book successfully deleted"


class BookList(ListView):
    model = Book
    template_name = "main/list.html"
    context_object_name = "books"
    paginate_by = 2


class BookDetail(DetailView):
    model = Book
    template_name = "main/detail.html"
    context_object_name = "book"


def multiplication_table(number, limit=10):
    table = []
    for i in range(1, limit + 1):
        table.append(f"{number} x {i} = {number * i}")
    return table


def dynamic_url_parameter(request):
    number = request.GET.get("number")
    if number.isdigit():
        multi_table = multiplication_table(int(number))
    else:
        multi_table = None
    context = {"multi_table": multi_table, "number": number, "active": "numbers"}
    return render(request, "main/dynamic_parameter.html", context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8">
		<meta name="theme-color" content="#7975FC" />
		<meta name="description" content="">
		<meta name="robots" content="{% block robots %}index, follow{% endblock %}">
		<title>Simple Project | {% block title %}{% endblock %}</title>
		{% include 'base/css.html' %}
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
		<link rel="apple-touch-icon" href="{% static 'img/favicon.ico' %}">
	</head>
	<body>
		<a href="#" id="scrollToTopBtn" class="scrollToTopBtn"></a>
		<div id="preloader"></div>
		{% include 'base/navbar.html' %}
		<div id="page-container">
			{% block content %}
			{% endblock %}
		</div>

		{% include 'base/footer.html' %}
		{% include 'base/js.html' %}
		{% include 'base/messages.html' %}
	</body>
</html>

templates/base/css.html
{% load static %}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"
    integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- Custom styles -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/base/footer.html
{% load static %}
<footer class="text-center">
    <div class="container">
        <div class="row mt-4">
            <hr>
            <p>Developed By <a class="link-style" href="https://abdelrahman.era-coding.com/" target="_blank">Abdelrahman Mamdouh</a></p>
            <p>&copy; CopyRight 2024  <a class="link-style" href="/">Simple Project</a>. All Rights Reserved.</p>
            <hr>
        </div>
    </div>
</footer>

templates/base/forms/create_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{% if object %} Edit {{ object }} {% else %} Create New object {% endif %}
{% endblock %}
{% block content %}

<div class="d-flex flex-row align-items-center">
    <div class="container mt-5 card">
        <div class="col-md-12 text-center mt-4">
            {% if object %}
            <h1>Edit {{ object }}</h1>
            {% else %}
                <h1>Create New Object</h1>
            {% endif %}
        </div>
        
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-danger" id="back-page">Cancel</span></a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/base/forms/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Delete {{ object }}
{% endblock %}
{% block content %}

<div class="d-flex flex-row align-items-center">
    <div class="container mt-5 card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <h3 class="alert alert-warning">Delete {{ object }}</h3>
                <p class="lead text-danger">This action cannot be undone</p>
                <button class="btn btn-danger" type="submit">Yes delete</button>
                <a class="btn btn-primary" id="back-page">Cancel</span></a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/base/js.html
{% load static %}
<!-- Bootstrap JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.min.js"
    integrity="sha512-3dZ9wIrMMij8rOH7X3kLfXAzwtcHpuYpEgQg1OA4QAob1e81H8ntUQmQm3pBudqIoySO5j0tHN4ENzA6+n2r4w=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Sweet alerts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.7.11/sweetalert2.all.min.js"
    integrity="sha512-sZf2OK8od53udtGBBdzSqg3BGjjL3BpM5K4dQgB0mmhumO07aWOLmBK917w5cbdLWPfILjJzKgJcYm+neEBUDw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- Custom scripts -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

templates/base/messages.html
{% load i18n %}
{% if messages %}
    {% if messages|length > 1 %}
        <script>
            Swal.fire({
                {% for message in messages %}
                icon: "{{ message.tags }}",
                title: '{% if message.tags == "error" %}{% trans "Error!" %}{% elif message.tags == "success" %}{% trans "Success" %}{% elif message.tags == "warning" %}{% trans "Warning" %}{% else %}{% trans "Info" %}{% endif %}',
                {% endfor %}
                html: "<ul class='errorlist'>{% for message in messages %}<li {% if message.tags == 'success'%}class='successlist'{% endif %}>{{ message }}</li>{% endfor %}</ul>",
                confirmButtonText: '{% trans "OK" %}',
                confirmButtonColor: '#269ffd',

            });
        </script>
    {% else %}
        {% for message in messages %}
        <script>
            Swal.fire({
                icon: "{{ message.tags }}",
                title: '{% if message.tags == "error" %}{% trans "Error!" %}{% elif message.tags == "success" %}{% trans "Success" %}{% elif message.tags == "warning" %}{% trans "Warning" %}{% else %}{% trans "Info" %}{% endif %}',
                html: "<h4>{{ message }}</h4>",
                confirmButtonText: '{% trans "OK" %}',
                confirmButtonColor: '#269ffd',

            });
        </script>
        {% endfor %}
    {% endif %}
{% endif %}

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse w-100" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if active == 'home' %}active{% endif %}" aria-current="page" href="/"> Home</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto w-100 justify-content-end">
                {% if user.is_authenticated %}
                    {% if user.is_superuser or user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-external-link-alt"></i> Go to admin</a>
                    </li>
                    {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link {% if active == 'books' %}active{% endif %}" href="{% url 'main:book_list' %}">CRUD Operations Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active == 'numbers' %}active{% endif %}" href="{% url 'main:dynamic_url_parameter' %}?number=1">Dynamic URL Parameter Page</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/base/pagination.html
{% if objects.has_other_pages %}
<div class="col-12 pagi">
    <nav>
        <ul class="pagination">
            {% if objects.has_previous %}
            <li class="page-item">
                <a class="page-link prev" href="?page={{ objects.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true"><</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" aria-label="Previous">
                    <span aria-hidden="true"><</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}
            {% for i in objects.paginator.page_range %}
            {% if objects.number > 2 and forloop.first %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            <li class="page-item disabled"><a class="page-link me-2" href="&page=1">...</a></li>
            {% endif %}
            {% if objects.number == i %}
            <li class="page-item"><a class="page-link pagination-active" href="#">{{ i }}</a></li>
            {% elif i > objects.number|add:'-2' and i < objects.number|add:'2' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% if objects.paginator.num_pages > objects.number|add:'1' and forloop.last %}
            <li class="page-item disabled"><a class="page-link">...</a></li>
            <li class="page-item">
                <a class="page-link me-2"
                    href="?page={{ objects.paginator.num_pages }}">{{ objects.paginator.num_pages }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if objects.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ objects.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" aria-label="Next">
                    <span aria-hidden="true">></span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}
{% block content %}


<div class="d-flex flex-row align-items-center" style="min-height: 80vh;">
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h1 class="display-1">Hello</h1>
                <p class="lead">This is a simple django project</p>
                <a href="{% url 'main:book_list' %}" class="btn btn-primary">CRUD Operations Page</a>
                <a href="#" class="btn btn-success">Dynamic URL Parameter Page</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
     {{ book }}
{% endblock %}
{% block content %}

<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <a class="btn btn-primary" href="{% url 'main:home' %}"><i class="fa-solid fa-house fa-lg"></i></a>
        <a class="btn btn-success" href="{% url 'main:book_create' %}">Create New Book</a>
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="card">
                    <img src="{% if book.image %}{{ book.image.url }}{% else %}{% static 'img/no-image.jpg' %}{% endif %}" class="card-img-top" alt="{{ book.title }}">
                    <div class="card-body">
                      <h5 class="card-title">{{ book.title }}</h5>
                      <p class="card-text">Author: {{ book.author }}</p>
                      <p class="card-text">Created By: {% if book.created_by %}{{ book.created_by }}{% else %} Anonymous user{% endif %}</p>
                      <p class="card-text">Created At: {{ book.created_at }}</p>
                      <p class="card-text">Last Updated: {{ book.updated_at }}</p>
                      <a href="{% url 'main:book_delete' book.pk %}" class="btn btn-danger">Delete Book</a>
                      <a href="{% url 'main:book_update' book.pk %}" class="btn btn-primary">Update Book</a>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/dynamic_parameter.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Dynamic URL Parameter Page
{% endblock %}
{% block content %}

<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <a class="btn btn-primary" href="{% url 'main:home' %}"><i class="fa-solid fa-house fa-lg"></i></a>
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">Multiplication Table For {{ number }}</h5>
                      <p class="text-info">Change number parameter to get other tables.</p>
                      {% if multi_table %}
                      <p class="card-text"> {% for line in multi_table %}{{ line }} <br> {% endfor %}</p>
                      {% else %}
                      <p class="text-danger">number parameter must be a number</p>
                      {% endif %}
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}
{% block content %}

<div class="d-flex flex-row align-items-center">
    <div class="container mt-5">
        <a class="btn btn-primary" href="{% url 'main:home' %}"><i class="fa-solid fa-house fa-lg"></i></a>
        <a class="btn btn-success" href="{% url 'main:book_create' %}">Create New Book</a>
        <div class="row">
            {% for book in books %}
            <div class="col-md-6 mt-4 mb-3">
                <div class="card">
                    <img src="{% if book.image %}{{ book.image.url }}{% else %}{% static 'img/no-image.jpg' %}{% endif %}" class="card-img-top" alt="{{ book.title }}">
                    <div class="card-body">
                      <h5 class="card-title">{{ book.title }}</h5>
                      <p class="card-text">Author: {{ book.author }}</p>
                      <a href="{{ book.get_absolute_url }}" class="btn btn-primary">View Details</a>
                    </div>
                  </div>
            </div>
            {% empty %}
                <p class="text-danger fs-5">No books found.</p>
            {% endfor %}
        </div>
        {% include 'base/pagination.html' with objects=page_obj %}
    </div>
</div>

{% endblock %}